export const metadata = {
  title: '關於我們',
  description: 'Generated by create next app',
}

export default function AboutLayout({ children }) {
  return (
    <div>
      <h1>關於區layout</h1>
      {children}
    </div>
  )
}
