export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Provider from './provider'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
