export const metadata = {
  title: '會員區',
  description: 'Generated by create next app',
}
import Menubar from './admin/menubar/menuBar'
export default function AdminLayout({ children }) {
  return (
    <>
      <div>
        <Menubar />
      </div>
      <div>{children}</div>
    </>
  )
}
