export const metadata = {
  title: '管理區',
  description: 'Generated by create next app',
}
import Menubar from './dashboard/menubar/menuBar'
export default function DashboardLayout({ children }) {
  return (
    <>
      <div>
        <Menubar />
      </div>
      <div>{children}</div>
    </>
  )
}
